//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColdWarCamo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class AssaultRifles : global::System.Configuration.ApplicationSettingsBase {
        
        private static AssaultRifles defaultInstance = ((AssaultRifles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AssaultRifles())));
        
        public static AssaultRifles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Last {
            get {
                return ((int)(this["Last"]));
            }
            set {
                this["Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string XM4_LEVEL {
            get {
                return ((string)(this["XM4_LEVEL"]));
            }
            set {
                this["XM4_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string XM4_CAMO_MP {
            get {
                return ((string)(this["XM4_CAMO_MP"]));
            }
            set {
                this["XM4_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string XM4_CAMO_ZM {
            get {
                return ((string)(this["XM4_CAMO_ZM"]));
            }
            set {
                this["XM4_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string XM4_STATS_MP {
            get {
                return ((string)(this["XM4_STATS_MP"]));
            }
            set {
                this["XM4_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string XM4_STATS_ZM {
            get {
                return ((string)(this["XM4_STATS_ZM"]));
            }
            set {
                this["XM4_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AK47_LEVEL {
            get {
                return ((string)(this["AK47_LEVEL"]));
            }
            set {
                this["AK47_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string AK47_CAMO_MP {
            get {
                return ((string)(this["AK47_CAMO_MP"]));
            }
            set {
                this["AK47_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string AK47_CAMO_ZM {
            get {
                return ((string)(this["AK47_CAMO_ZM"]));
            }
            set {
                this["AK47_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string AK47_STATS_MP {
            get {
                return ((string)(this["AK47_STATS_MP"]));
            }
            set {
                this["AK47_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string AK47_STATS_ZM {
            get {
                return ((string)(this["AK47_STATS_ZM"]));
            }
            set {
                this["AK47_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string KRIG6_LEVEL {
            get {
                return ((string)(this["KRIG6_LEVEL"]));
            }
            set {
                this["KRIG6_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string KRIG6_CAMO_MP {
            get {
                return ((string)(this["KRIG6_CAMO_MP"]));
            }
            set {
                this["KRIG6_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string KRIG6_CAMO_ZM {
            get {
                return ((string)(this["KRIG6_CAMO_ZM"]));
            }
            set {
                this["KRIG6_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string KRIG6_STATS_MP {
            get {
                return ((string)(this["KRIG6_STATS_MP"]));
            }
            set {
                this["KRIG6_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string KRIG6_STATS_ZM {
            get {
                return ((string)(this["KRIG6_STATS_ZM"]));
            }
            set {
                this["KRIG6_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string QBZ83_LEVEL {
            get {
                return ((string)(this["QBZ83_LEVEL"]));
            }
            set {
                this["QBZ83_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string QBZ83_CAMO_MP {
            get {
                return ((string)(this["QBZ83_CAMO_MP"]));
            }
            set {
                this["QBZ83_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string QBZ83_CAMO_ZM {
            get {
                return ((string)(this["QBZ83_CAMO_ZM"]));
            }
            set {
                this["QBZ83_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string QBZ83_STATS_MP {
            get {
                return ((string)(this["QBZ83_STATS_MP"]));
            }
            set {
                this["QBZ83_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string QBZ83_STATS_ZM {
            get {
                return ((string)(this["QBZ83_STATS_ZM"]));
            }
            set {
                this["QBZ83_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string FFAR1_LEVEL {
            get {
                return ((string)(this["FFAR1_LEVEL"]));
            }
            set {
                this["FFAR1_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string FFAR1_CAMO_MP {
            get {
                return ((string)(this["FFAR1_CAMO_MP"]));
            }
            set {
                this["FFAR1_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string FFAR1_CAMO_ZM {
            get {
                return ((string)(this["FFAR1_CAMO_ZM"]));
            }
            set {
                this["FFAR1_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string FFAR1_STATS_MP {
            get {
                return ((string)(this["FFAR1_STATS_MP"]));
            }
            set {
                this["FFAR1_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string FFAR1_STATS_ZM {
            get {
                return ((string)(this["FFAR1_STATS_ZM"]));
            }
            set {
                this["FFAR1_STATS_ZM"] = value;
            }
        }
    }
}
