//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColdWarCamo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Pistols : global::System.Configuration.ApplicationSettingsBase {
        
        private static Pistols defaultInstance = ((Pistols)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Pistols())));
        
        public static Pistols Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Last {
            get {
                return ((int)(this["Last"]));
            }
            set {
                this["Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string M1911_LEVEL {
            get {
                return ((string)(this["M1911_LEVEL"]));
            }
            set {
                this["M1911_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string M1911_CAMO_MP {
            get {
                return ((string)(this["M1911_CAMO_MP"]));
            }
            set {
                this["M1911_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string M1911_CAMO_ZM {
            get {
                return ((string)(this["M1911_CAMO_ZM"]));
            }
            set {
                this["M1911_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string M1911_STATS_MP {
            get {
                return ((string)(this["M1911_STATS_MP"]));
            }
            set {
                this["M1911_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string M1911_STATS_ZM {
            get {
                return ((string)(this["M1911_STATS_ZM"]));
            }
            set {
                this["M1911_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MAGNUM_LEVEL {
            get {
                return ((string)(this["MAGNUM_LEVEL"]));
            }
            set {
                this["MAGNUM_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string MAGNUM_CAMO_MP {
            get {
                return ((string)(this["MAGNUM_CAMO_MP"]));
            }
            set {
                this["MAGNUM_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string MAGNUM_CAMO_ZM {
            get {
                return ((string)(this["MAGNUM_CAMO_ZM"]));
            }
            set {
                this["MAGNUM_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string MAGNUM_STATS_MP {
            get {
                return ((string)(this["MAGNUM_STATS_MP"]));
            }
            set {
                this["MAGNUM_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string MAGNUM_STATS_ZM {
            get {
                return ((string)(this["MAGNUM_STATS_ZM"]));
            }
            set {
                this["MAGNUM_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DIAMATTI_LEVEL {
            get {
                return ((string)(this["DIAMATTI_LEVEL"]));
            }
            set {
                this["DIAMATTI_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string DIAMATTI_CAMO_MP {
            get {
                return ((string)(this["DIAMATTI_CAMO_MP"]));
            }
            set {
                this["DIAMATTI_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string DIAMATTI_CAMO_ZM {
            get {
                return ((string)(this["DIAMATTI_CAMO_ZM"]));
            }
            set {
                this["DIAMATTI_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string DIAMATTI_STATS_MP {
            get {
                return ((string)(this["DIAMATTI_STATS_MP"]));
            }
            set {
                this["DIAMATTI_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string DIAMATTI_STATS_ZM {
            get {
                return ((string)(this["DIAMATTI_STATS_ZM"]));
            }
            set {
                this["DIAMATTI_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AMP63_LEVEL {
            get {
                return ((string)(this["AMP63_LEVEL"]));
            }
            set {
                this["AMP63_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string AMP63_CAMO_MP {
            get {
                return ((string)(this["AMP63_CAMO_MP"]));
            }
            set {
                this["AMP63_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string AMP63_CAMO_ZM {
            get {
                return ((string)(this["AMP63_CAMO_ZM"]));
            }
            set {
                this["AMP63_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string AMP63_STATS_MP {
            get {
                return ((string)(this["AMP63_STATS_MP"]));
            }
            set {
                this["AMP63_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string AMP63_STATS_ZM {
            get {
                return ((string)(this["AMP63_STATS_ZM"]));
            }
            set {
                this["AMP63_STATS_ZM"] = value;
            }
        }
    }
}
