//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColdWarCamo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Reticles : global::System.Configuration.ApplicationSettingsBase {
        
        private static Reticles defaultInstance = ((Reticles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Reticles())));
        
        public static Reticles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Last {
            get {
                return ((int)(this["Last"]));
            }
            set {
                this["Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string MILLSTOPREFLEX_MP {
            get {
                return ((string)(this["MILLSTOPREFLEX_MP"]));
            }
            set {
                this["MILLSTOPREFLEX_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string MILLSTOPREFLEX_ZM {
            get {
                return ((string)(this["MILLSTOPREFLEX_ZM"]));
            }
            set {
                this["MILLSTOPREFLEX_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string VISIONTECH2X_MP {
            get {
                return ((string)(this["VISIONTECH2X_MP"]));
            }
            set {
                this["VISIONTECH2X_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string VISIONTECH2X_ZM {
            get {
                return ((string)(this["VISIONTECH2X_ZM"]));
            }
            set {
                this["VISIONTECH2X_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string KOBRAREDDOT_MP {
            get {
                return ((string)(this["KOBRAREDDOT_MP"]));
            }
            set {
                this["KOBRAREDDOT_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string KOBRAREDDOT_ZM {
            get {
                return ((string)(this["KOBRAREDDOT_ZM"]));
            }
            set {
                this["KOBRAREDDOT_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string QUICKDOTLED_MP {
            get {
                return ((string)(this["QUICKDOTLED_MP"]));
            }
            set {
                this["QUICKDOTLED_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string QUICKDOTLED_ZM {
            get {
                return ((string)(this["QUICKDOTLED_ZM"]));
            }
            set {
                this["QUICKDOTLED_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string AXIALARMS3X_MP {
            get {
                return ((string)(this["AXIALARMS3X_MP"]));
            }
            set {
                this["AXIALARMS3X_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string AXIALARMS3X_ZM {
            get {
                return ((string)(this["AXIALARMS3X_ZM"]));
            }
            set {
                this["AXIALARMS3X_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string SILLIXHOLOSCOUT_MP {
            get {
                return ((string)(this["SILLIXHOLOSCOUT_MP"]));
            }
            set {
                this["SILLIXHOLOSCOUT_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string SILLIXHOLOSCOUT_ZM {
            get {
                return ((string)(this["SILLIXHOLOSCOUT_ZM"]));
            }
            set {
                this["SILLIXHOLOSCOUT_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string MICROFLEXLED_MP {
            get {
                return ((string)(this["MICROFLEXLED_MP"]));
            }
            set {
                this["MICROFLEXLED_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string MICROFLEXLED_ZM {
            get {
                return ((string)(this["MICROFLEXLED_ZM"]));
            }
            set {
                this["MICROFLEXLED_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string HAWKSMOOR_MP {
            get {
                return ((string)(this["HAWKSMOOR_MP"]));
            }
            set {
                this["HAWKSMOOR_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string HAWKSMOOR_ZM {
            get {
                return ((string)(this["HAWKSMOOR_ZM"]));
            }
            set {
                this["HAWKSMOOR_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string ROYALKROSS4X_MP {
            get {
                return ((string)(this["ROYALKROSS4X_MP"]));
            }
            set {
                this["ROYALKROSS4X_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string ROYALKROSS4X_ZM {
            get {
                return ((string)(this["ROYALKROSS4X_ZM"]));
            }
            set {
                this["ROYALKROSS4X_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string SUSATMULTIZOOM_MP {
            get {
                return ((string)(this["SUSATMULTIZOOM_MP"]));
            }
            set {
                this["SUSATMULTIZOOM_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string SUSATMULTIZOOM_ZM {
            get {
                return ((string)(this["SUSATMULTIZOOM_ZM"]));
            }
            set {
                this["SUSATMULTIZOOM_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string DIAMONDBACKREFLEX_MP {
            get {
                return ((string)(this["DIAMONDBACKREFLEX_MP"]));
            }
            set {
                this["DIAMONDBACKREFLEX_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string DIAMONDBACKREFLEX_ZM {
            get {
                return ((string)(this["DIAMONDBACKREFLEX_ZM"]));
            }
            set {
                this["DIAMONDBACKREFLEX_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string SNAPPOINT_MP {
            get {
                return ((string)(this["SNAPPOINT_MP"]));
            }
            set {
                this["SNAPPOINT_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string SNAPPOINT_ZM {
            get {
                return ((string)(this["SNAPPOINT_ZM"]));
            }
            set {
                this["SNAPPOINT_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string FASTPOINTREFLEX_MP {
            get {
                return ((string)(this["FASTPOINTREFLEX_MP"]));
            }
            set {
                this["FASTPOINTREFLEX_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string FASTPOINTREFLEX_ZM {
            get {
                return ((string)(this["FASTPOINTREFLEX_ZM"]));
            }
            set {
                this["FASTPOINTREFLEX_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string HANGMANRF_MP {
            get {
                return ((string)(this["HANGMANRF_MP"]));
            }
            set {
                this["HANGMANRF_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string HANGMANRF_ZM {
            get {
                return ((string)(this["HANGMANRF_ZM"]));
            }
            set {
                this["HANGMANRF_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string OTEROMINIREFLEX_MP {
            get {
                return ((string)(this["OTEROMINIREFLEX_MP"]));
            }
            set {
                this["OTEROMINIREFLEX_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|0000000000")]
        public string OTEROMINIREFLEX_ZM {
            get {
                return ((string)(this["OTEROMINIREFLEX_ZM"]));
            }
            set {
                this["OTEROMINIREFLEX_ZM"] = value;
            }
        }
    }
}
