//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColdWarCamo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class RocketLaunchers : global::System.Configuration.ApplicationSettingsBase {
        
        private static RocketLaunchers defaultInstance = ((RocketLaunchers)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RocketLaunchers())));
        
        public static RocketLaunchers Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Last {
            get {
                return ((int)(this["Last"]));
            }
            set {
                this["Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string CIGMA2_LEVEL {
            get {
                return ((string)(this["CIGMA2_LEVEL"]));
            }
            set {
                this["CIGMA2_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string CIGMA2_CAMO_MP {
            get {
                return ((string)(this["CIGMA2_CAMO_MP"]));
            }
            set {
                this["CIGMA2_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string CIGMA2_CAMO_ZM {
            get {
                return ((string)(this["CIGMA2_CAMO_ZM"]));
            }
            set {
                this["CIGMA2_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string CIGMA2_STATS_MP {
            get {
                return ((string)(this["CIGMA2_STATS_MP"]));
            }
            set {
                this["CIGMA2_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string CIGMA2_STATS_ZM {
            get {
                return ((string)(this["CIGMA2_STATS_ZM"]));
            }
            set {
                this["CIGMA2_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string RPG7_LEVEL {
            get {
                return ((string)(this["RPG7_LEVEL"]));
            }
            set {
                this["RPG7_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string RPG7_CAMO_MP {
            get {
                return ((string)(this["RPG7_CAMO_MP"]));
            }
            set {
                this["RPG7_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string RPG7_CAMO_ZM {
            get {
                return ((string)(this["RPG7_CAMO_ZM"]));
            }
            set {
                this["RPG7_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string RPG7_STATS_MP {
            get {
                return ((string)(this["RPG7_STATS_MP"]));
            }
            set {
                this["RPG7_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string RPG7_STATS_ZM {
            get {
                return ((string)(this["RPG7_STATS_ZM"]));
            }
            set {
                this["RPG7_STATS_ZM"] = value;
            }
        }
    }
}
