//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColdWarCamo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Shotguns : global::System.Configuration.ApplicationSettingsBase {
        
        private static Shotguns defaultInstance = ((Shotguns)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Shotguns())));
        
        public static Shotguns Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Last {
            get {
                return ((int)(this["Last"]));
            }
            set {
                this["Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string HAUER77_LEVEL {
            get {
                return ((string)(this["HAUER77_LEVEL"]));
            }
            set {
                this["HAUER77_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string HAUER77_CAMO_MP {
            get {
                return ((string)(this["HAUER77_CAMO_MP"]));
            }
            set {
                this["HAUER77_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string HAUER77_CAMO_ZM {
            get {
                return ((string)(this["HAUER77_CAMO_ZM"]));
            }
            set {
                this["HAUER77_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string HAUER77_STATS_MP {
            get {
                return ((string)(this["HAUER77_STATS_MP"]));
            }
            set {
                this["HAUER77_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string HAUER77_STATS_ZM {
            get {
                return ((string)(this["HAUER77_STATS_ZM"]));
            }
            set {
                this["HAUER77_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string GALLOSA12_LEVEL {
            get {
                return ((string)(this["GALLOSA12_LEVEL"]));
            }
            set {
                this["GALLOSA12_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string GALLOSA12_CAMO_MP {
            get {
                return ((string)(this["GALLOSA12_CAMO_MP"]));
            }
            set {
                this["GALLOSA12_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string GALLOSA12_CAMO_ZM {
            get {
                return ((string)(this["GALLOSA12_CAMO_ZM"]));
            }
            set {
                this["GALLOSA12_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string GALLOSA12_STATS_MP {
            get {
                return ((string)(this["GALLOSA12_STATS_MP"]));
            }
            set {
                this["GALLOSA12_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string GALLOSA12_STATS_ZM {
            get {
                return ((string)(this["GALLOSA12_STATS_ZM"]));
            }
            set {
                this["GALLOSA12_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string STREETSWEEPER_LEVEL {
            get {
                return ((string)(this["STREETSWEEPER_LEVEL"]));
            }
            set {
                this["STREETSWEEPER_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string STREETSWEEPER_CAMO_MP {
            get {
                return ((string)(this["STREETSWEEPER_CAMO_MP"]));
            }
            set {
                this["STREETSWEEPER_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string STREETSWEEPER_CAMO_ZM {
            get {
                return ((string)(this["STREETSWEEPER_CAMO_ZM"]));
            }
            set {
                this["STREETSWEEPER_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string STREETSWEEPER_STATS_MP {
            get {
                return ((string)(this["STREETSWEEPER_STATS_MP"]));
            }
            set {
                this["STREETSWEEPER_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string STREETSWEEPER_STATS_ZM {
            get {
                return ((string)(this["STREETSWEEPER_STATS_ZM"]));
            }
            set {
                this["STREETSWEEPER_STATS_ZM"] = value;
            }
        }
    }
}
