//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColdWarCamo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SniperRifles : global::System.Configuration.ApplicationSettingsBase {
        
        private static SniperRifles defaultInstance = ((SniperRifles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SniperRifles())));
        
        public static SniperRifles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Last {
            get {
                return ((int)(this["Last"]));
            }
            set {
                this["Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PELINGTON703_LEVEL {
            get {
                return ((string)(this["PELINGTON703_LEVEL"]));
            }
            set {
                this["PELINGTON703_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string PELINGTON703_CAMO_MP {
            get {
                return ((string)(this["PELINGTON703_CAMO_MP"]));
            }
            set {
                this["PELINGTON703_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string PELINGTON703_CAMO_ZM {
            get {
                return ((string)(this["PELINGTON703_CAMO_ZM"]));
            }
            set {
                this["PELINGTON703_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string PELINGTON703_STATS_MP {
            get {
                return ((string)(this["PELINGTON703_STATS_MP"]));
            }
            set {
                this["PELINGTON703_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string PELINGTON703_STATS_ZM {
            get {
                return ((string)(this["PELINGTON703_STATS_ZM"]));
            }
            set {
                this["PELINGTON703_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string LW3TUNDRA_LEVEL {
            get {
                return ((string)(this["LW3TUNDRA_LEVEL"]));
            }
            set {
                this["LW3TUNDRA_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string LW3TUNDRA_CAMO_MP {
            get {
                return ((string)(this["LW3TUNDRA_CAMO_MP"]));
            }
            set {
                this["LW3TUNDRA_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string LW3TUNDRA_CAMO_ZM {
            get {
                return ((string)(this["LW3TUNDRA_CAMO_ZM"]));
            }
            set {
                this["LW3TUNDRA_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string LW3TUNDRA_STATS_MP {
            get {
                return ((string)(this["LW3TUNDRA_STATS_MP"]));
            }
            set {
                this["LW3TUNDRA_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string LW3TUNDRA_STATS_ZM {
            get {
                return ((string)(this["LW3TUNDRA_STATS_ZM"]));
            }
            set {
                this["LW3TUNDRA_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string M82_LEVEL {
            get {
                return ((string)(this["M82_LEVEL"]));
            }
            set {
                this["M82_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string M82_CAMO_MP {
            get {
                return ((string)(this["M82_CAMO_MP"]));
            }
            set {
                this["M82_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string M82_CAMO_ZM {
            get {
                return ((string)(this["M82_CAMO_ZM"]));
            }
            set {
                this["M82_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string M82_STATS_MP {
            get {
                return ((string)(this["M82_STATS_MP"]));
            }
            set {
                this["M82_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string M82_STATS_ZM {
            get {
                return ((string)(this["M82_STATS_ZM"]));
            }
            set {
                this["M82_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ZRG20MM_LEVEL {
            get {
                return ((string)(this["ZRG20MM_LEVEL"]));
            }
            set {
                this["ZRG20MM_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string ZRG20MM_CAMO_MP {
            get {
                return ((string)(this["ZRG20MM_CAMO_MP"]));
            }
            set {
                this["ZRG20MM_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string ZRG20MM_CAMO_ZM {
            get {
                return ((string)(this["ZRG20MM_CAMO_ZM"]));
            }
            set {
                this["ZRG20MM_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string ZRG20MM_STATS_MP {
            get {
                return ((string)(this["ZRG20MM_STATS_MP"]));
            }
            set {
                this["ZRG20MM_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string ZRG20MM_STATS_ZM {
            get {
                return ((string)(this["ZRG20MM_STATS_ZM"]));
            }
            set {
                this["ZRG20MM_STATS_ZM"] = value;
            }
        }
    }
}
