//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColdWarCamo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SubmachineGuns : global::System.Configuration.ApplicationSettingsBase {
        
        private static SubmachineGuns defaultInstance = ((SubmachineGuns)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SubmachineGuns())));
        
        public static SubmachineGuns Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Last {
            get {
                return ((int)(this["Last"]));
            }
            set {
                this["Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MP5_LEVEL {
            get {
                return ((string)(this["MP5_LEVEL"]));
            }
            set {
                this["MP5_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string MP5_CAMO_MP {
            get {
                return ((string)(this["MP5_CAMO_MP"]));
            }
            set {
                this["MP5_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string MP5_CAMO_ZM {
            get {
                return ((string)(this["MP5_CAMO_ZM"]));
            }
            set {
                this["MP5_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string MP5_STATS_MP {
            get {
                return ((string)(this["MP5_STATS_MP"]));
            }
            set {
                this["MP5_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string MP5_STATS_ZM {
            get {
                return ((string)(this["MP5_STATS_ZM"]));
            }
            set {
                this["MP5_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MILANO821_LEVEL {
            get {
                return ((string)(this["MILANO821_LEVEL"]));
            }
            set {
                this["MILANO821_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string MILANO821_CAMO_MP {
            get {
                return ((string)(this["MILANO821_CAMO_MP"]));
            }
            set {
                this["MILANO821_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string MILANO821_CAMO_ZM {
            get {
                return ((string)(this["MILANO821_CAMO_ZM"]));
            }
            set {
                this["MILANO821_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string MILANO821_STATS_MP {
            get {
                return ((string)(this["MILANO821_STATS_MP"]));
            }
            set {
                this["MILANO821_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string MILANO821_STATS_ZM {
            get {
                return ((string)(this["MILANO821_STATS_ZM"]));
            }
            set {
                this["MILANO821_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AK74U_LEVEL {
            get {
                return ((string)(this["AK74U_LEVEL"]));
            }
            set {
                this["AK74U_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string AK74U_CAMO_MP {
            get {
                return ((string)(this["AK74U_CAMO_MP"]));
            }
            set {
                this["AK74U_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string AK74U_CAMO_ZM {
            get {
                return ((string)(this["AK74U_CAMO_ZM"]));
            }
            set {
                this["AK74U_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string AK74U_STATS_MP {
            get {
                return ((string)(this["AK74U_STATS_MP"]));
            }
            set {
                this["AK74U_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string AK74U_STATS_ZM {
            get {
                return ((string)(this["AK74U_STATS_ZM"]));
            }
            set {
                this["AK74U_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string KSP45_LEVEL {
            get {
                return ((string)(this["KSP45_LEVEL"]));
            }
            set {
                this["KSP45_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string KSP45_CAMO_MP {
            get {
                return ((string)(this["KSP45_CAMO_MP"]));
            }
            set {
                this["KSP45_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string KSP45_CAMO_ZM {
            get {
                return ((string)(this["KSP45_CAMO_ZM"]));
            }
            set {
                this["KSP45_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string KSP45_STATS_MP {
            get {
                return ((string)(this["KSP45_STATS_MP"]));
            }
            set {
                this["KSP45_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string KSP45_STATS_ZM {
            get {
                return ((string)(this["KSP45_STATS_ZM"]));
            }
            set {
                this["KSP45_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BULLFROG_LEVEL {
            get {
                return ((string)(this["BULLFROG_LEVEL"]));
            }
            set {
                this["BULLFROG_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string BULLFROG_CAMO_MP {
            get {
                return ((string)(this["BULLFROG_CAMO_MP"]));
            }
            set {
                this["BULLFROG_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string BULLFROG_CAMO_ZM {
            get {
                return ((string)(this["BULLFROG_CAMO_ZM"]));
            }
            set {
                this["BULLFROG_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string BULLFROG_STATS_MP {
            get {
                return ((string)(this["BULLFROG_STATS_MP"]));
            }
            set {
                this["BULLFROG_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string BULLFROG_STATS_ZM {
            get {
                return ((string)(this["BULLFROG_STATS_ZM"]));
            }
            set {
                this["BULLFROG_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MAC10_LEVEL {
            get {
                return ((string)(this["MAC10_LEVEL"]));
            }
            set {
                this["MAC10_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string MAC10_CAMO_MP {
            get {
                return ((string)(this["MAC10_CAMO_MP"]));
            }
            set {
                this["MAC10_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string MAC10_CAMO_ZM {
            get {
                return ((string)(this["MAC10_CAMO_ZM"]));
            }
            set {
                this["MAC10_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string MAC10_STATS_MP {
            get {
                return ((string)(this["MAC10_STATS_MP"]));
            }
            set {
                this["MAC10_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string MAC10_STATS_ZM {
            get {
                return ((string)(this["MAC10_STATS_ZM"]));
            }
            set {
                this["MAC10_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string LC10_LEVEL {
            get {
                return ((string)(this["LC10_LEVEL"]));
            }
            set {
                this["LC10_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string LC10_CAMO_MP {
            get {
                return ((string)(this["LC10_CAMO_MP"]));
            }
            set {
                this["LC10_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string LC10_CAMO_ZM {
            get {
                return ((string)(this["LC10_CAMO_ZM"]));
            }
            set {
                this["LC10_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string LC10_STATS_MP {
            get {
                return ((string)(this["LC10_STATS_MP"]));
            }
            set {
                this["LC10_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string LC10_STATS_ZM {
            get {
                return ((string)(this["LC10_STATS_ZM"]));
            }
            set {
                this["LC10_STATS_ZM"] = value;
            }
        }
    }
}
