//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColdWarCamo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class TacticalRifles : global::System.Configuration.ApplicationSettingsBase {
        
        private static TacticalRifles defaultInstance = ((TacticalRifles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TacticalRifles())));
        
        public static TacticalRifles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Last {
            get {
                return ((int)(this["Last"]));
            }
            set {
                this["Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TYPE63_LEVEL {
            get {
                return ((string)(this["TYPE63_LEVEL"]));
            }
            set {
                this["TYPE63_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string TYPE63_CAMO_MP {
            get {
                return ((string)(this["TYPE63_CAMO_MP"]));
            }
            set {
                this["TYPE63_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string TYPE63_CAMO_ZM {
            get {
                return ((string)(this["TYPE63_CAMO_ZM"]));
            }
            set {
                this["TYPE63_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string TYPE63_STATS_MP {
            get {
                return ((string)(this["TYPE63_STATS_MP"]));
            }
            set {
                this["TYPE63_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string TYPE63_STATS_ZM {
            get {
                return ((string)(this["TYPE63_STATS_ZM"]));
            }
            set {
                this["TYPE63_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string M16_LEVEL {
            get {
                return ((string)(this["M16_LEVEL"]));
            }
            set {
                this["M16_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string M16_CAMO_MP {
            get {
                return ((string)(this["M16_CAMO_MP"]));
            }
            set {
                this["M16_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string M16_CAMO_ZM {
            get {
                return ((string)(this["M16_CAMO_ZM"]));
            }
            set {
                this["M16_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string M16_STATS_MP {
            get {
                return ((string)(this["M16_STATS_MP"]));
            }
            set {
                this["M16_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string M16_STATS_ZM {
            get {
                return ((string)(this["M16_STATS_ZM"]));
            }
            set {
                this["M16_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AUG_LEVEL {
            get {
                return ((string)(this["AUG_LEVEL"]));
            }
            set {
                this["AUG_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string AUG_CAMO_MP {
            get {
                return ((string)(this["AUG_CAMO_MP"]));
            }
            set {
                this["AUG_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string AUG_CAMO_ZM {
            get {
                return ((string)(this["AUG_CAMO_ZM"]));
            }
            set {
                this["AUG_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string AUG_STATS_MP {
            get {
                return ((string)(this["AUG_STATS_MP"]));
            }
            set {
                this["AUG_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string AUG_STATS_ZM {
            get {
                return ((string)(this["AUG_STATS_ZM"]));
            }
            set {
                this["AUG_STATS_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DMR14_LEVEL {
            get {
                return ((string)(this["DMR14_LEVEL"]));
            }
            set {
                this["DMR14_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string DMR14_CAMO_MP {
            get {
                return ((string)(this["DMR14_CAMO_MP"]));
            }
            set {
                this["DMR14_CAMO_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000000000000000000000000000000")]
        public string DMR14_CAMO_ZM {
            get {
                return ((string)(this["DMR14_CAMO_ZM"]));
            }
            set {
                this["DMR14_CAMO_ZM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string DMR14_STATS_MP {
            get {
                return ((string)(this["DMR14_STATS_MP"]));
            }
            set {
                this["DMR14_STATS_MP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0,0,0,0")]
        public string DMR14_STATS_ZM {
            get {
                return ((string)(this["DMR14_STATS_ZM"]));
            }
            set {
                this["DMR14_STATS_ZM"] = value;
            }
        }
    }
}
